name: Upload Release Asset

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  release:
    types:
      - created


jobs:
  build:
    name: Upload Release Asset
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Runs on pushes but not on releases
        if: github.event_name != 'release'
        run: echo 'test'
      - name: Upload Release Asset
        if: github.event_name == 'release'
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./Book2.xlsm
          asset_name: Book2-${{ github.event.release.tag_name }}.xlsm
          asset_content_type: application/zip